include: "rules/common.smk"


rule all:
    input:
        "results/vase_filtered/vase_filtered.all.vcf.gz",
        "results/report/vase_filtered.report.json",
        "results/report/vase_filtered.report.xlsx",


include: "rules/vase.smk"
