vcf: test/test.vcf.gz
ped: test/HG002.ped

dbsnp: test/dbsnp/dbSNP_sample.vcf.gz
gnomad: test/gnomad/gnomad_r2.1.1_wes_chr21_chr22.less_info.vcf.gz
splice_ai_dir: test/splice_ai_scores
cadd_dir: test/cadd

annotating:
    extra: ""

filtering:
  recessive:
    freq: 0.005
    gq: 20
    dp: 5
    het_vaf: 0.25
    hom_vaf: 0.9
    con_het_vaf: 0.1
    con_hom_vaf: 0.8
    csq: "default splice_region_variant"
  dominant:
    freq: 0.0001
    gq: 20
    dp: 5
    het_vaf: 0.25
    con_vaf: 0.1
    max_con_ref_vaf: 0.05
    csq: "default"
  de_novo:
    freq: 0.0001
    gq: 20
    dp: 5
    het_vaf: 0.25
    con_vaf: 0.1
    max_con_ref_vaf: 0.05
    csq: "default splice_region_variant"
    extra: ""

report:
    extra: "--grch37 --rest_lookups --mygene_lookups -t 5" 
